### ISSUE TITLE
Значки соц сетей, при нажатии, не пропадает тень

### ISSUE THREAD

**Issue by Nika987** [diglabby/Falanster-site#108]
@amoebiusss @Omeljusik 
https://monosnap.com/file/nakRZWJjkVkIINACe65t8oMsgcf7xl

**Comment by Omeljusik** [comment]
Гэта не пра аранжывую цень, і цень на чорным фоне гэта не страшна) Міні-баг, калі ен есць, таму не будзем вырашаць)
