### ISSUE TITLE
Firefox| Кнопки Запоуниць анкету, Дапамагчы обрамлены прерывистой рамкой после нажатия в браузере кнопки назад (minor)

### ISSUE THREAD

**Issue by Nika987** [diglabby/Falanster-site#109]
@Omeljusik @amoebiusss 
https://monosnap.com/file/k2cj92xGl19XWndBWwseRgDLfZsRnq

**Comment by siarohin** [comment]
@Nika987 @Omeljusik Аналогично https://github.com/diglabby/Falanster-site/issues/116 Протестируйте, не должно быть бага.

**Comment by Nika987** [comment]
@siarohin 
Проблема осталась, добавилась прерывистые рамки при нажатии на кнопки.
Вложение: https://monosnap.com/file/mGF9XZCgCkTWEbZbPsMwfIt4xLkWe7

**Comment by siarohin** [comment]
https://github.com/diglabby/Falanster-site/pull/156

**Comment by Omeljusik** [comment]
зараз праблемы няма
