### ISSUE TITLE
Firefox| В блоке Стань Валанцерам остается белый фон после нажатия в браузере кнопки назад

### ISSUE THREAD

**Issue by Nika987** [diglabby/Falanster-site#110]
@Omeljusik @amoebiusss 
https://monosnap.com/file/Em3qSQ4kEszrHmkAsqd4i7WJg3EvhZ

**Comment by Omeljusik** [comment]
@Nika987 Вітаю, я праглядзела ў FF, там не так ідэальна як на хром, але калі няма заліпання і чагосьці страшэннага, то нічога страшэннага. Я схільна пакінуць.
