### ISSUE TITLE
Edge|  Firefox| В футере поле подписацца на нас и кнопка ОК не подсвечиваются рамки синим цветом при вводе email и при нажатии ОК

### ISSUE THREAD

**Issue by Nika987** [diglabby/Falanster-site#111]
@Omeljusik @siarohin 
https://monosnap.com/file/cVjFrhfcJ0SfGGjkKBHGD9uPTnlfx0

**Comment by Omeljusik** [comment]
@Nika987 Можна тэсціраваць.

**Comment by Nika987** [comment]
@siarohin 
Поле - ок.
кнопка ОК не подсвечивает.
