### ISSUE TITLE
Opera| В футере не подсвечивается рамка синим цветом при нажатии ОК

### ISSUE THREAD

**Issue by Nika987** [diglabby/Falanster-site#112]
@Omeljusik @siarohin 
https://monosnap.com/file/DVw3WHUG5XEqZFZZMebRTVV5r3Hbjl

**Comment by siarohin** [comment]
@Nika987 А в других браузерах подсвечивается при таком сценарии?

**Comment by Nika987** [comment]
@siarohin 
только в chrome

**Comment by siarohin** [comment]
@Nika987 что-то тут не так, и в хроме не должно. Фокус то пропал с элемента. Запись на Хроме пожалуйста при том же сценарии, пойму что имеете ввиду.

**Comment by siarohin** [comment]
Синяя подсветка - это стандартное поведение элемента, мы фичили только красную.

**Comment by siarohin** [comment]
вы про это?

![default](https://user-images.githubusercontent.com/38830168/52667676-2b159280-2f1a-11e9-9269-54882901dc93.PNG) -- есть фокус в хроме

![2](https://user-images.githubusercontent.com/38830168/52667706-42ed1680-2f1a-11e9-9cc2-de6cb70020b1.PNG) -- нет фокуса в хроме

**Comment by Nika987** [comment]
@siarohin 
Поясняю простыми словами))):
изначально когда в поле вводился электронный адрес, в поле рамка выделялась красным цветом, что было неверно. Сейчас вместо красного синий. 
https://monosnap.com/file/8nLoHlsgv2o9TPKCw0uakrw9r0UgBk

**Comment by siarohin** [comment]
@Nika987 вижу что при нажатии на ОК синий пропадает - так и должно быть, в общем, тестируйте #111: https://github.com/diglabby/Falanster-site/pull/121

**Comment by Omeljusik** [comment]
@Nika987 хай лепей падсвечваецца, калі так атрымліваецца ў некаторых браўзерах. Зачыняю.
