### ISSUE TITLE
Десктоп. Неверно указаны брейкпоинты в style.css на главной странице 

### ISSUE THREAD

**Issue by Nika987** [diglabby/Falanster-site#115]
@amoebiusss 
https://monosnap.com/file/tbpPmIi5XdSwxGlk38VIzMs40o2O1c

**Comment by Omeljusik** [comment]
@Nika987 Вітаю, 
пішы, калі ласка, таксама не толькі праблему, але чакаемы рузультат.

**Comment by amoebiusss** [comment]
@Nika987 @Omeljusik Этот брейкпоинт автор изначальной верстки сделал для очень больших экранов, чтобы проекты выстраивались в один ряд. Правда, в макетах и в ТЗ я упоминаний о таком поведении не увидела, возможно это как-то на словах оговаривалось

**Comment by Omeljusik** [comment]
@Nika987 @amoebiusss Так, верна. Зачыняю іш'ю.
