### ISSUE TITLE
Firefox| Внутренняя страница "Пра нас". Десктоп. При возврате на страницу вокруг логотип обрамлен прерывистой рамкой. (minor)

### ISSUE THREAD

**Issue by Nika987** [diglabby/Falanster-site#116]
@Omeljusik @siarohin 
https://monosnap.com/file/v8qfsd3YljGWPCjU5ymmnsZSZJ48z4 

Ожидаемый результат: При возврате на страницу логотип остается в прежнем состоянии, т.е. без какого-либо обрамление.

**Comment by siarohin** [comment]
@Nika987 Буду тестировать, когда появится в мастер ветке. Он и не должен скакать, останется в кэше.

**Comment by siarohin** [comment]
@Nika987 @Omeljusik Этот баг должен был пофикситься, когда пофиксилось залипание оранжевой кнопки `Стать волонтером`. Причина у них одинаковая. Проверьте. Со своей стороны протестировал, проблемы не выявил.

**Comment by Nika987** [comment]
@ShiningSoldier 
Сейчас эта рамка появляется при нажатии на кнопки.
Вложение: https://monosnap.com/file/mGF9XZCgCkTWEbZbPsMwfIt4xLkWe7

**Comment by siarohin** [comment]
https://github.com/diglabby/Falanster-site/pull/156

**Comment by Omeljusik** [comment]
зараз праблемы няма
