### ISSUE TITLE
При перешагивании по значкам в разделе меню внизу окна браузера появляется вспышка-полоса   

### ISSUE THREAD

**Issue by Nika987** [diglabby/Falanster-site#117]
@amoebiusss 
https://monosnap.com/file/YokRY8NPCKW5KzHbLGeDGTxe8bczCe 

Ожидаемый результат: На главной и внутренней страницах нет никаких проявлений при перешагивании по значкам в разделе меню.

**Comment by amoebiusss** [comment]
@Nika987 это браузерная индикация урла ссылки. Можно проверить на любом другом сайте, наводя курсор на любую ссылку на странице

**Comment by Nika987** [comment]
@amoebiusss @Omeljusik 
Да, я согласна с Вашим замечанием. 
Но все же, мне кажется, здесь что-то не так с параметрами настройки индексирования.
Обычно на браузерную индикацию урла ссылки пользователь не обращает внимание, т.к. она незаметна его глазу. В нашем случае, она обращает на себя внимание. Но это на ваше усмотрение, если вы считаете это правильным.

**Comment by Omeljusik** [comment]
@Nika987 Можна тэсціраваць.

**Comment by Nika987** [comment]
@amoebiusss 
Проблема осталась.

**Comment by Nika987** [comment]
@amoebiusss 
все ок
