### ISSUE TITLE
Внутренняя страница. Ссылки в тексте имеют изначально оранжевый шрифт.

### ISSUE THREAD

**Issue by Nika987** [diglabby/Falanster-site#118]
@siarohin 
https://monosnap.com/file/yvxFezupHYhlJ3CNU66NedXw5ykM40 
Ожидаемый результат: ссылка в тексте - 333333 подчеркнута, при наведении оранжевый ff6600 подчеркнута.

**Comment by siarohin** [comment]
@amoebiusss Пофиксишь? Это шаблон about ,который в твоем репо

**Comment by amoebiusss** [comment]
сделаю
не совсем поняла из макета, что это состояние при наведении

**Comment by Nika987** [comment]
@amoebiusss 
Я дополнительно уточню, как получу ответ сразу же напишу.

**Comment by Nika987** [comment]
@amoebiusss 
Все ссылки в тексте имеют цвет 33333 и они подчеркнуты, при наведении курсора изменяется цвет на оранжевый и он подчеркнутый, а при нажатии на ссылку оранжевый цвет остается и убирается подчеркивание.

**Comment by Omeljusik** [comment]
Дубляванне з #127
