### ISSUE TITLE
[Галоўная старонка] Замяніць малюнкі пад спасылкамі Запоўніць анкету і Дапамагчы і малюнак злева у блоке Гарачыя Праекты на css. 

### ISSUE THREAD

**Issue by Omeljusik** [diglabby/Falanster-site#122]
Гэта робіцца праз псеўдаэлементы праз ::before і ::after. Прыліпанне к секцыі.

**Comment by amoebiusss** [comment]
Запоўніць анкету і Дапамагчы  — можно это еще бордером сделать как вариант (сделала так в своем альтернативном варианте верстки главной страницы)

**Comment by Omeljusik** [comment]
@amoebiusss добра, можна і так, 
але калі вы добра ведаеце, як зрабіць так, каб гэта падкрэсліванне было звязана са словам пад якім стаіць. Буду ўдзячна.

**Comment by amoebiusss** [comment]
Единственное - сейчас подчеркивания у Запоўніць анкету і Дапамагчы и так сделаны псевдоэлементами. А в чем проблема с интеграцией? Не совсем понимаю, что именно исправлять

![image](https://user-images.githubusercontent.com/26903136/52769998-036e1980-3043-11e9-9445-001804e5bb8b.png)

**Comment by Omeljusik** [comment]
@amoebiusss @siarohin зразумела, дзякуй. 
Зачыняю іш'ю. 
@ossset
