### ISSUE TITLE
[Галоўная старонка] Дадаць дэкарытыўныя малюнкі ў секцыю каляндара згодна макету.

### ISSUE THREAD

**Issue by Omeljusik** [diglabby/Falanster-site#123]
Пакуль няма psd. Толькі малюнак https://realtimeboard.com/app/board/o9J_kzircGQ=/?moveToWidget=3074457346361667952. 

Запрасіла psd альбо дасканалае апісанне ў @nastyafrosty. Чакаем.

**Comment by Omeljusik** [comment]
@siarohin Прывітанне,
запытаю вас зрабіць як Насц psd. Ці добра ведаеце як зправіцца з такой задачай?

**Comment by nastyafrosty** [comment]
@Omeljusik исходя из названия issue не понимаю,описание чего нужно?

**Comment by Omeljusik** [comment]
@nastyafrosty усе што не модуль і не функцыянал. Палосачкі)

**Comment by Omeljusik** [comment]
@siarohin аформіце, калі ласка, блок з каляндаром як тут. https://github.com/nastyafrosty/Falanster_new_website/blob/master/Main%20page/Calendar.psd

Белы бэкграўнд і злева палосачкі праз css. Сам каляндар і дойку адлюстроўваць не рэба, бо гэта модулі, якія потым дададуцца.

P.S. На выпадака калі можна неяк удічыць у верстке (задаць нешта ў ей), напішу, што каляндар пры націску на падзею разгортваецца гармошкай уніз і блог расцягваецца ўніз падстаріваюцыся пад разгорнуты каляндарю

**Comment by siarohin** [comment]
@Omeljusik @Nika987 https://github.com/diglabby/Falanster-site/pull/145
