### ISSUE TITLE
Внутренняя страница. Брекпоинты max-width: 1079px

### ISSUE THREAD

**Issue by Nika987** [diglabby/Falanster-site#125]
@amoebiusss 
Вложение: https://monosnap.com/file/JjpsRTmLRsPzoH7zmoEISAjzDdSgM0 

Ожидаемый результат:
Десктоп - > 1080 px
Смартфон - 320px - 1080p

**Comment by amoebiusss** [comment]
@Omeljusik Изначально на всех страницах был использован брейкпоинт max-width: 1079px (до 1080 невключительно). Если менять, то везде. Эти изменения нужны?

**Comment by Omeljusik** [comment]
@Nika987 @amoebiusss не, не трэба.
Зачыняю іш'ю.
