### ISSUE TITLE
Внутренняя страница. При нажатии на скрол основной текст второго экрана появляется со второго предложения.

### ISSUE THREAD

**Issue by Nika987** [diglabby/Falanster-site#126]
@amoebiusss 
Вложение: https://monosnap.com/file/KoQ7Awc1GB1ivPxbf97WSFCR3noruV 

Ожидаемый результат: основной текст виден сначала, блок меню не закрывает первое предложение.

**Comment by Omeljusik** [comment]
@Nika987 удакладню. Таксама можаце дадаваць скрыны.
@amoebiusss Пасля скрола (пры націску на кнопку "уніз"), трэба каб меню не зачыняла сабой верхнюю частку другога экрана. Атрымліваецца, што меню спускаецца да пачатку першага экрана. 
Малюнак:
![image](https://user-images.githubusercontent.com/32821205/52786827-fa923d80-306c-11e9-8857-92aba88f1aca.png)

**Comment by amoebiusss** [comment]
@Omeljusik да, думаю над решением пока

**Comment by amoebiusss** [comment]
https://github.com/diglabby/Falanster-site/pull/139

**Comment by Omeljusik** [comment]
@amoebiusss 
Зараз так 
![image](https://user-images.githubusercontent.com/32821205/52952638-38a59f00-3396-11e9-8a08-861dad63e059.png)

Трэба, каб было так 
![image](https://user-images.githubusercontent.com/32821205/52952670-5bd04e80-3396-11e9-994b-64baaa59d902.png)

Меню не зачыняе сабой другі экран пасля скрола.

**Comment by Omeljusik** [comment]
@Nika987 Можна зноў тэсціраваць.
