### ISSUE TITLE
Внутренняя страница. Ссылки в тексте не соответствуют требованиям.

### ISSUE THREAD

**Issue by Nika987** [diglabby/Falanster-site#127]
@amoebiusss 

Ожидаемый результат: все ссылки в тексте имеют черный цвет и они подчеркнуты, при наведении курсора изменяется черный цвет на оранжевый, а при нажатии на ссылку оранжевый цвет остается и убирается подчеркивание.

**Comment by Nika987** [comment]
@amoebiusss 
Я еще дополнительно уточню, как получу ответ сразу же напишу.

**Comment by Nika987** [comment]
@amoebiusss 
Все ссылки в тексте имеют цвет 33333 и они подчеркнуты, при наведении курсора изменяется цвет на оранжевый и он подчеркнутый, а при нажатии на ссылку оранжевый цвет остается и убирается подчеркивание.

**Comment by amoebiusss** [comment]
@Nika987 @Omeljusik  дублирование https://github.com/diglabby/Falanster-site/issues/118
