### ISSUE TITLE
Внутренняя страница. При валидации  выявлены ошибки.

### ISSUE THREAD

**Issue by Nika987** [diglabby/Falanster-site#128]
@siarohin 
Вложение: https://monosnap.com/file/XMHxwt2Tql7cHtfZBFuuPfnumMtg0H

Ожидаемый результат: не выявлено ошибок.

**Comment by amoebiusss** [comment]
Ошибка притянулась из верстки главной — при добавлении рассылки не закрыли тег form.
Исправления в ПР https://github.com/diglabby/Falanster-site/pull/131

**Comment by Nika987** [comment]
@amoebiusss 
Примечание: 
Warning: Section lacks heading. Consider using h2-h6 elements to add identifying headings to all sections.

From line 163, column 5; to line 163, column 38

ion>↩↩    <section class="about" id="about">↩
