### ISSUE TITLE
Поле для ввода электронной почты имеет закругления 1рх

### ISSUE THREAD

**Issue by Nika987** [diglabby/Falanster-site#129]
@siarohin 
Ожидаемый результат: 3рх

**Comment by siarohin** [comment]
@Nika987 Уточните задачу, вижу 3px сейчас
![default](https://user-images.githubusercontent.com/38830168/52787812-bb152280-3067-11e9-92ef-354586346e6e.PNG)

**Comment by Nika987** [comment]
@siarohin 
https://monosnap.com/file/ucJfLhEWJ4e2WVcrFnNgKTTTVtxvGR

**Comment by siarohin** [comment]
@Nika987 ok

**Comment by Nika987** [comment]
@siarohin 
ok
