### ISSUE TITLE
[Унутранняя старонка] Змяніць эфект кнопак пры навядзенні і націску такім жа як на галоўнай "Чытаць пра нас"

### ISSUE THREAD

**Issue by Omeljusik** [diglabby/Falanster-site#134]
Пры навядзенні кнопка павялічваецца. Пры націску - зменяецца колер бэкграўнда на белы, а слова на аранжавы.

**Comment by amoebiusss** [comment]
@Omeljusik ок. Дальше все оранжевые кнопки делаем именно с таким эффектом?

**Comment by Omeljusik** [comment]
@amoebiusss Так. Выбачайце, што доўга адказваю, бо рэдка праглядаю пошту. Калі нешта тэрміновае, то паведамляйце, калі ласка, яшчэ ў слэк. Я буду старацца часцей праглядаць іш'ю.

**Comment by amoebiusss** [comment]
https://github.com/diglabby/Falanster-site/pull/163
