### ISSUE TITLE
[Унутранняя старонка] Зрабіць змены Первага экрана старонкі Блога згодна абноўленнаму макету

### ISSUE THREAD

**Issue by Omeljusik** [diglabby/Falanster-site#135]
### ТЗ для запіса Блога (Афішы) ибо psd может быть не идеальным. Если есть серьезные расхождения, то спрашивайте @nastyafrosty 
Шрифт заголовка: Ubuntu, medium, 60px, межстрок - 68px. 
Заголовок с датай публикации и автором выравнивается по середине между прямоугольником с датой и меню. 
![image](https://user-images.githubusercontent.com/32821205/52854873-f3ccfe80-3130-11e9-8407-804ff2abd466.png)
Если появляется вторая строчка, то выравнивание по левому краю рабочей области
Указание автора и даты на расстоянии 60px от заголовка, шрифт Ubuntu Regular 14px. Промежуток от даты до автора 40px. Дата и автор указываются слева на одном уровне с заголовком.

Скролла вниз нет!

**Comment by amoebiusss** [comment]
@Omeljusik т.е. скролл остается только на странице "о нас"? или вообще не остается?

**Comment by Omeljusik** [comment]
@amoebiusss на старонке Пра нас і Праект. 
Убіраецца толькі ў Блозе.

**Comment by Omeljusik** [comment]
@Nika987 можна тэсціраваць.
