### ISSUE TITLE
Внутренняя страница. Текст, заголовки. Шрифт Ubuntu

### ISSUE THREAD

**Issue by Nika987** [diglabby/Falanster-site#140]
@siarohin 
Вложение: https://monosnap.com/file/A6OjLftwF094ypEwOPcR22f4pebHBX
Ожидаемый результат: Text Pt Sans Regular. Head 1, Head 2 - PT Sans Bold

**Comment by amoebiusss** [comment]
@Nika987 точно, спасибо, поправила

**Comment by Nika987** [comment]
@amoebiusss 
ok
