### ISSUE TITLE
Внутренняя страница. Назва мерапрыемства. Содержание страницы не соответствует макету, т.е. второй экран не содержит текста, блока для комментариев и т.д.

### ISSUE THREAD

**Issue by Nika987** [diglabby/Falanster-site#141]
@amoebiusss 
Вложение: https://monosnap.com/file/s1fCv0lXrAtiGRuhr1Gj7CXxSJMefX
Ожидаемый результат: второй экран, согласно макету: текст, комментарии и т.д.

**Comment by amoebiusss** [comment]
@Nika987 комментарии - это отдельный подключаемый модуль

**Comment by Omeljusik** [comment]
так, не баг, зачыняю.
