### ISSUE TITLE
Внутренняя страница. Назва мерапрыемства. На первом экране слова аутар заменить на аўтар

### ISSUE THREAD

**Issue by Nika987** [diglabby/Falanster-site#142]
@siarohin 
Вложение: https://monosnap.com/file/nA7TY2ygnOfWcrcMHJ5XqQjQMc9Wi5 
Ожидаемый результат: правильно написано слова аутар по-белорусски - аўтар.

**Comment by amoebiusss** [comment]
@Nika987 я копирую текст из макета, не перепечатываю вручную. Могу поправить, но это в любом случае текст-"рыба", который потом заменится реальным контентом

**Comment by Nika987** [comment]
@amoebiusss 
Если Вам не сложно, то лучше замените.
Спасибо!)

**Comment by Omeljusik** [comment]
@amoebiusss неабавязкова, зачыняю іш'ю
