### ISSUE TITLE
Внутренняя страница. Градка. Отредактировать отступы, согласно макету.

### ISSUE THREAD

**Issue by Nika987** [diglabby/Falanster-site#143]
@amoebiusss @Omeljusik 
Ожидаемый результат: отступы, согласно макету. 
https://github.com/Omeljusik/Hello-world/blob/master/pixels.png

P.S. Прошлась по отступам в CSS везде не соответствие.

**Comment by amoebiusss** [comment]
@Nika987 а как именно вы проверяете или меряете отступы? По ссылке отступы обозначены как отступ + высота строки, поэтому абсолютные значения в цсс будут отличаться. Перепроверьте, пожалуйста

**Comment by Nika987** [comment]
@amoebiusss 
Я могу ошибаться, но я смотрю в scc:
например, margin-bottom: 110px 
Вложение: https://monosnap.com/file/lubs1upehBozLPWVXYSWakgJbuEaM4 

Если судить по макету, на мой взгляд, здесь должно быть 120рх.
Как Вы думаете ?

**Comment by amoebiusss** [comment]
@Nika987 margin-bottom у блока .content — это нижний внешний отступ всего блока с контентом; по макету 110 пикселей

**Comment by Omeljusik** [comment]
@Nika987 @amoebiusss @nastyafrosty Праглядзела проста візуальна і верхні і ніжні адлегласці і параўнала проста па выгляду - з макетам суадносіцца. У мяне пытанняў няма, таму зачыняю іш'ю.
