### ISSUE TITLE
[Унутранняя старонка] Кнопка скрол уніз працуе неверна пасля націску на яе Пасля скрола Мышкай ўніз.

### ISSUE THREAD

**Issue by Omeljusik** [diglabby/Falanster-site#147]
https://github.com/Omeljusik/Pictures-for-external-sites/blob/master/Screencast%202019-02-18.mp4 спасылка на тое, каб спампаваць відэа экрана.

Шагі:
1. Пралістаць няшмат (2-4 руха калесікам) мышкай уніз.
2. Нажаць на кнопку скрола ўніз.

**Comment by Omeljusik** [comment]
@Nika987 Праглядзі, калі ласка, таксама.

**Comment by Nika987** [comment]
@Omeljusik 
Праглядзела. Гэта баг. Старонка павiнна унiз пайсцi, а яна уверх паузе. Я бы прыярытэт
павысiла.

**Comment by amoebiusss** [comment]
https://monosnap.com/file/NQmTBYubpZMQyTc5jnvr4tPkKod9Wz
