### ISSUE TITLE
[Галоўная старонка] Пры пераходзе на каляндар, меню зачыняе верхнюю часку блока "Каляндар"

### ISSUE THREAD

**Issue by Omeljusik** [diglabby/Falanster-site#148]
![image](https://user-images.githubusercontent.com/32821205/52958461-2aab4a80-33a5-11e9-99fb-3794779d1ad4.png)

Трэба каб меню астанаўлівалася ўнізе папярэдняга блока, не заходзячы на блок Каляндар.
Тое ж самае, як ва ўнутранніх старонках.

Так, будзе верна
![image](https://user-images.githubusercontent.com/32821205/52958707-b3c28180-33a5-11e9-9747-ab349d9d04be.png)

**Comment by amoebiusss** [comment]
https://github.com/diglabby/Falanster-site/pull/164
