### ISSUE TITLE
[Галоўная старонка] Адсутнічае полупразрыстасць пры навядзенні на Гарачы праект. 

### ISSUE THREAD

**Issue by Omeljusik** [diglabby/Falanster-site#149]
![image](https://user-images.githubusercontent.com/32821205/52958981-46fbb700-33a6-11e9-9d06-fd93340f6917.png)

Трэба, каб было 
![image](https://user-images.githubusercontent.com/32821205/52959170-a4900380-33a6-11e9-8fb0-19c4836bcb10.png)

**Comment by Omeljusik** [comment]
@Nika987 можна тэсціраваць

**Comment by Nika987** [comment]
@Omeljusik 
Я правильно понимаю полупрозрачность должна быть только при наведении на проект, т.е. проект должен быть иметь обычный фон, но при наведении на его меняется на полупрозрачный?

**Comment by Nika987** [comment]
@Omeljusik @siarohin 
ok
