### ISSUE TITLE
[Унутранная старонка] Зрабіць больш плаўны каляровы пераход ад першага экрана к другому. Дадаць градыента.

### ISSUE THREAD

**Issue by Omeljusik** [diglabby/Falanster-site#155]
Сама задача састаіт у тым каб зрабіць пераход больш плаўным. 

У мяне есць 2 варыянта:
1. Лепшы варыяні: Зрабіць прыкладна як тут https://it.falanster.by/blog/2019/02/15/chamu-linux/, але можа не так шмат (на глаз як больш плаўна і прыгожа). Эфект таксама з'яўляецца пры пралістванні ўніз. Калі поўнасцю вяртаемся наверх, то ён знікае.
2. 1/4 малюнка пераходзіць на Другую старонку і зроблена градыентам (спачатку больш празрыста і там дзе тэкст і далей да канца малюнак бачна ўсё менш). 

Зараз пераход вельмі рэзкі: 
![image](https://user-images.githubusercontent.com/32821205/53094207-910da580-352a-11e9-8e20-20cbb73b0d6e.png)

Магчыма ёсць і іншыя варыянты...

**Comment by nastyafrosty** [comment]
поскольку,как я понимаю, мы ограничены в ресурсах и времени, мне кажется,что можно сделать,как на сайте майстэрни

**Comment by Omeljusik** [comment]
@siarohin Гляньце гэту задачку, калі ласка, адпішыцесь, што думаеце? Ці яна зразумела?

**Comment by ossset** [comment]
Ребята, сделайте градиент на всю фотку (т.е. чтобы мнимое начало градиента начиналось от навбара) а сам переход сделайте где он и должен быть по макету и все получится. т.е. чтобы белый градиент был над фоткой с затемнением.

Примерно так.
![image](https://user-images.githubusercontent.com/32739281/53165957-16559080-35e5-11e9-8987-08d31aebf6d3.png)
