### ISSUE TITLE
[Унутраная старонка] Адсутнічае мяжа для дліны слова ў загалоўке. Трэба зрабіць, каб слова не выходзіла за межы працоўнай вобласці з тэкстам 778 px

### ISSUE THREAD

**Issue by Omeljusik** [diglabby/Falanster-site#157]
![image](https://user-images.githubusercontent.com/32821205/53097320-3ed08280-3532-11e9-860c-0d7dd6749131.png)

**Comment by Omeljusik** [comment]
Перанос часткі слова на наступную страку (пажадана праз -). Але толькі, пры ўмове, што гэта адно слова на ўсю строку, якое не змяшчаецца (такое можа быць, калі слова складанае праз працяжнік). Калі не змяшчаецца асобнае слова, яно пераносіцца на наступную строку.

**Comment by siarohin** [comment]
@Omeljusik https://github.com/diglabby/Falanster-site/pull/159

**Comment by Omeljusik** [comment]
@Nika987 Можна правяраць

**Comment by Nika987** [comment]
@Omeljusik @siarohin 
ok
