### ISSUE TITLE
Падлучыць падпicку. Пры пераходзе на дэфолтную старонку от майлчымпа пра тое, што падпіска амаль завершына, дапушчана некарэктнасць

### ISSUE THREAD

**Issue by Nika987** [diglabby/Falanster-site#160]
@Omeljusik 
Пытанне: Чаму ўжываеце займеннік свой у сказе "Нам трэба пацвердзіць свой адрас электроннай пошты"? Мне здаецца, карэктна ужываць займеннiк "ваш" альбо сфармаваць новы сказ:
"Нам трэба, каб ты (альбо Вы) пацвердзіу (альбо пацвердзілi) свой  адрас электроннай пошты."

Вложение: https://monosnap.com/file/QJPAWbPzl1dIKWs5E0Lqhye2FyuiU8

**Comment by Omeljusik** [comment]
@Nika987 я зачыняю, бо гэта не звязана з версткай. Это звязана з сервісам мэйл-чымп. Дадайце, калі лакска, у тэхнічныя задачы ў трэлло.
