### ISSUE TITLE
[Унутраная старонка] Дадаць блок "Вынікі праекта" на старонку project.html для дэсктопнай і мабільна версіі

### ISSUE THREAD

**Issue by Omeljusik** [diglabby/Falanster-site#167]
Макеты:
Дэсктоп https://github.com/nastyafrosty/Falanster_new_website/blob/master/Blog_projects/Project_results_desktop.psd
Смартфон https://github.com/nastyafrosty/Falanster_new_website/blob/master/Blog_projects/Project_results_mob.psd

В десктоп версии круг слева и квадрат справа залиты градиентом от ff6600 до ff8635

![image](https://user-images.githubusercontent.com/32821205/53184614-68f77280-360e-11e9-9d96-a1d8c4272c6a.png)

Адзінеае - тут памылка ў загалоўке. Трэба каб было "Вынікі праекта"

**Comment by amoebiusss** [comment]
https://github.com/diglabby/Falanster-site/pull/193

**Comment by Omeljusik** [comment]
@Nika987 Патрэбна тэставанне.
