### ISSUE TITLE
Внутренняя страница. При уменьшении размера экран обрамляется синей рамкой 

### ISSUE THREAD

**Issue by Nika987** [diglabby/Falanster-site#168]
@amoebiusss 
Вложение: https://monosnap.com/file/kIWay00Mwr28dU5nRevTTyxJw5iMY7 

Ожидаемый результат: при уменьшении размера у экрана отсутствуют обраменительные рамки.

**Comment by Omeljusik** [comment]
@Nika987 Прывітанне,
такое адбываецца з любым браўзерам у незалежнасці ад таго, на якім сайце мы знаходзімся.
