### ISSUE TITLE
Вн. стр. Градка. Прямоугольник, в котором обозначается статус проекта или клуба, не имеет закругления.

### ISSUE THREAD

**Issue by Nika987** [diglabby/Falanster-site#172]
@siarohin 
Ожидаемый результат: Все прямоугольные формы (кнопки, блоки проектов) имеют закругление в 3px

**Comment by amoebiusss** [comment]
см. комментарий https://github.com/diglabby/Falanster-site/issues/178#issuecomment-467408987
