### ISSUE TITLE
Вн.стр. Градка. Отсутствует тень прямоугольника со статусом проекта на 1-м экране.

### ISSUE THREAD

**Issue by Nika987** [diglabby/Falanster-site#173]
@siarohin 
Ожидаемый результат: есть тень прямоугольника со статусом проекта.
Вложение: https://monosnap.com/file/5WqbbGUT59upCtFuIWM6UgzzHyOqzv

**Comment by amoebiusss** [comment]
https://github.com/diglabby/Falanster-site/pull/194

**Comment by Omeljusik** [comment]
@Nika987 Вітаю,
трэба пратэсціраваць цень.
