### ISSUE TITLE
Вн.стр. Градка. Расстояние от статуса проекта до иконки - 15 pх

### ISSUE THREAD

**Issue by Nika987** [diglabby/Falanster-site#174]
@siarohin 
Вложение: https://monosnap.com/file/VNn5CLF21AieZDW9Ur6SMbZqvNvDsx 
Ожидаемый результат: расстояние от статуса проекта до иконки - 20px.

**Comment by amoebiusss** [comment]
@Nika987 померяйте абсолютное расстояние чем-нибудь типа PageRuler, не привязываясь к значению конкретного отступа

**Comment by Omeljusik** [comment]
@Nika987 На мой погляд так нават лепей, з тым як на макеце суадносіцца. 
Зачыняю іш'ю. Правак не трэба.
