### ISSUE TITLE
Вн.стр. Градка. Низ стрелки находится на уровне центра прямоугольника.

### ISSUE THREAD

**Issue by Nika987** [diglabby/Falanster-site#175]
@siarohin 
Вложение: https://monosnap.com/file/uZH560yCoeh1ppTmCpaHeghm1F6aSc 
Ожидаемый результат: низ стрелки находится на уровне низа прямоугольника 20px

**Comment by amoebiusss** [comment]
@Nika987 отступ от нижнего края и есть 20px
