### ISSUE TITLE
Вн.стр. Градка, Пра нас. Кнопка Стань валанцёрам не увеличиваться при наведении курсора.

### ISSUE THREAD

**Issue by Nika987** [diglabby/Falanster-site#176]
@siarohin 
Вложение: https://monosnap.com/file/dHn5kEvEgwY6HJSkFw7eeniDKGkRjm 
Ожидаемый результат: Кнопка Стань валанцёрам должна увеличиваться при наведении курсора (как на главной Чытаць пра нас).

**Comment by Omeljusik** [comment]
@Nika987 У мяне працуе. Магчыма трэба пачысціць кэш.
