### ISSUE TITLE
Вн.стр. Градка, Пра нас. Кнопка Стань валанцёрам имеет параметры 448х64

### ISSUE THREAD

**Issue by Nika987** [diglabby/Falanster-site#177]
@siarohin 
Вложение: https://monosnap.com/file/llJnJYDOXimDISxIlzeqAVBQCDXcer 
Ожидаемый результат: Дэсктоп: 420х64, Ubuntu 18,bold

**Comment by Omeljusik** [comment]
@Nika987 не баг. Усе як на макеце. 
![image](https://user-images.githubusercontent.com/32821205/53412038-4502ab00-39d9-11e9-92d0-1faba28c8886.png)
тут толькі height 36, а не 64. Але, калі рабіць 64, то кнопка атрымаецца вельмі жырнай) зроблена як на макеце)
