### ISSUE TITLE
Вн.стр.events. Прямоугольник с датой мероприятия не имеет закругления. 

### ISSUE THREAD

**Issue by Nika987** [diglabby/Falanster-site#178]
@siarohin
Ожидаемый результат: Все прямоугольные формы (кнопки, блоки проектов) имеют закругление в 3px.

**Comment by amoebiusss** [comment]
@Nika987 @Omeljusik в макете нет закруглений. это не блок проекта

![image](https://user-images.githubusercontent.com/26903136/53410815-e4be3a00-39d5-11e9-8e69-0ab741394849.png)
