### ISSUE TITLE
Вн.стр.events. Отсутствует тень у прямоугольника с датой мероприятия

### ISSUE THREAD

**Issue by Nika987** [diglabby/Falanster-site#179]
@siarohin
Ожидаемый результат: есть тень прямоугольника с датой мероприятия.

**Comment by amoebiusss** [comment]
+
давайте объединим ишью
 https://github.com/diglabby/Falanster-site/issues/173

**Comment by amoebiusss** [comment]
https://github.com/diglabby/Falanster-site/pull/194
