### ISSUE TITLE
Гл.стр. Ссылка Усе падзеi не меняет цвет

### ISSUE THREAD

**Issue by Nika987** [diglabby/Falanster-site#180]
@siarohin 
Вложение: https://monosnap.com/file/cUcLOeda5WSX0a6RKtxzu8TWuKkjoA 
Ожидаемый результат: все ссылки в тексте подчеркнуты, при наведении курсора на ссылку меняется цвет подчеркнутость остается, при нажатии на ссылку подчеркнутость убирается.

**Comment by siarohin** [comment]
@Omeljusik Уточните, эту ссылку меняем или оставляем как сейчас?

**Comment by Omeljusik** [comment]
> @Omeljusik Уточните, эту ссылку меняем или оставляем как сейчас?
@siarohin так, гэта лепей паправіць, бо гэта стандартнае рашэнне для падкрэсліных спасылак па ўсяму сайту

**Comment by Omeljusik** [comment]
@Nika987 патрэбна тэставанне.
