### ISSUE TITLE
Футер. “Правілы сайта”, “FAQ”, “Зрабі ўнесак”, “Кантакты” отсутствует при наведении шрифт 20px, при нажатии цвет # ff6600

### ISSUE THREAD

**Issue by Nika987** [diglabby/Falanster-site#181]
@siarohin 
Вложение: https://monosnap.com/file/p559wYsIBNGNfBC8l0UycsMdxbrBWd 
Ожидаемый результат: согласно требованиям ТЗ - “Правілы сайта”, “FAQ”, “Зрабі ўнесак”, “Кантакты” - Ubuntu, regular, 18px, #ffffff; при наведении шрифт 20px, при нажатии цвет # ff6600

**Comment by Omeljusik** [comment]
@Nika987  Вітаю, 
можна тэсціраваць

**Comment by Nika987** [comment]
@Omeljusik @siarohin 
у меня ничего не работает, как и было

**Comment by Nika987** [comment]
@Omeljusik @siarohin 
все ок
