### ISSUE TITLE
Хедер. Мы - кам сац наватарау имеет шрифт 25

### ISSUE THREAD

**Issue by Nika987** [diglabby/Falanster-site#182]
@siarohin 
Вложение: https://monosnap.com/file/b7YNS4mx6J0bKUtXCYtQ3Z5XRo7c2b
Ожидаемый результат: 24 рх

**Comment by Omeljusik** [comment]
@Nika987 выглядае добра. Меней дакладна не трэба, бо на вялікіх экранах, шрыўт падаецца нават маленькім.
