### ISSUE TITLE
Гл.стр. Гарачыя праекты. Даведацца больш (на кнопке) шрифт 15 рх

### ISSUE THREAD

**Issue by Nika987** [diglabby/Falanster-site#183]
@siarohin 
Вложение: https://monosnap.com/file/DPMRadvnxd33t61Z1Fs0cqgB2Y7ycw 
Ожидаемый результат: 16 рх

**Comment by Omeljusik** [comment]
@Nika987 выглядае добра, нічога страшэннага.
Зачыню. Можа быць зноў адчынена як скончым нашу асноўную працу.
