### ISSUE TITLE
Гарачыя праекты. Назвы праектаў, апісанне праектаў не соответствует цвет шрифта

### ISSUE THREAD

**Issue by Nika987** [diglabby/Falanster-site#184]
@siarohin 
Вложение: https://monosnap.com/file/1rSRX9C2ou2afx5h6GiqU4ThujyhVs 
Ожидаемый результат: согласно требованиям ТЗ Блок 1. Праекты:
Назвы праектаў -  Ubuntu, medium, #333333, 24px
Апісанне праектаў - Pt Sans, regular, #333333, 16px

**Comment by Omeljusik** [comment]
@Nika987 Не, пакідаем усе як есць - у патрабаваннях было апісана неверна наконт колера. Arial нічым не адрозніваецца. Зроблена згодна макету.
