### ISSUE TITLE
Блог. День, дата, автор не соответствует шрифт PT Sans

### ISSUE THREAD

**Issue by Nika987** [diglabby/Falanster-site#185]
@siarohin 
Вложение:  https://monosnap.com/file/s9QkVfahOTovdoXvUPuZ23jQ5sVE1a
Ожидаемый результат: согласно требованиям ТЗ Блок 3. Блог:
день, дата, автор -  Ubuntu, regular, #898989, 14px

**Comment by Omeljusik** [comment]
@Nika987 выглядае добра, нічога страшэннага.
Зачыню. Можа быць зноў адчынена для паляпшэння як скончым нашу асноўную працу.
