### ISSUE TITLE
Блог. Усе падзеi не соответствует цвет шрифта 090909 

### ISSUE THREAD

**Issue by Nika987** [diglabby/Falanster-site#186]
@siarohin 
Вложение: https://monosnap.com/file/Xo6KFhUQ3rKJcaAPqaWBk0OWo72xfz
Ожидаемый результат: согласно требованиям ТЗ Блок 3. Блог:
Усе падзеі, - Ubuntu, regular, #333333, 18px

**Comment by Omeljusik** [comment]
@Nika987 выглядае добра, нічога страшэннага.
Зачыню. Можа быць зноў адчынена для паляпшэння як скончым нашу асноўную працу.
