### ISSUE TITLE
Стань валанцёрам не соответствует шрифт 45

### ISSUE THREAD

**Issue by Nika987** [diglabby/Falanster-site#187]
@siarohin 
Вложение: https://monosnap.com/file/Xo6KFhUQ3rKJcaAPqaWBk0OWo72xfz
Ожидаемый результат: согласно требованиям ТЗ Блок 4. Стань валанцерам:
Стань валанцерам! - Ubuntu, medium, #ffffff, 48px

**Comment by Omeljusik** [comment]
@Nika987 алоўная ведь ужо пратэсціравана - мы аддалі інтэграцыю; + выглядае добра, нічога страшэннага.
Зачыню. Можа быць зноў адчынена для паляпшэння як скончым нашу асноўную працу.
