### ISSUE TITLE
Стань валанцерам шрифт текста и его цвет обозначен PT Sans 17 px

### ISSUE THREAD

**Issue by Nika987** [diglabby/Falanster-site#188]
@siarohin 
Вложение: https://monosnap.com/file/tthRokHfn1RRF89rGHXFakQ0RLFblR
Ожидаемый результат: согласно требованиям ТЗ Блок 4. Стань валанцерам:
текст - Ubuntu, medium, #333333, 18px

**Comment by Omeljusik** [comment]
@Nika987 выглядае добра, нічога страшэннага.
Зачыню. Можа быць зноў адчынена як скончым нашу асноўную працу.
