### ISSUE TITLE
Футер. Кнопка ОК имеет шрифт 16

### ISSUE THREAD

**Issue by Nika987** [diglabby/Falanster-site#189]
@siarohin 
Вложение: https://monosnap.com/file/Piz0jQDWcHJcZ6emzjVSXtdSdKQkkQ
Ожидаемый результат: согласно требованиям ТЗ Футер:
“ok” - Ubuntu, regular, 18px, заглавными буквами, #898989

**Comment by Omeljusik** [comment]
@Nika987 выглядае добра, нічога страшэннага. 
Зачыню. Можа быць зноў адчынена як скончым нашу асноўную працу.
