### ISSUE TITLE
[Прамежкавая старонка] Зрабіць вёрстку для Дэсктопа.

### ISSUE THREAD

**Issue by Omeljusik** [diglabby/Falanster-site#190]
Усяго тры варыянты
## Фаланстэр
Макет https://github.com/nastyafrosty/Falanster_new_website/blob/master/Blog_projects/2nd%20level%20-%20ORGANISATION%20desktop.psd

## Праекты+Клубы 
https://github.com/nastyafrosty/Falanster_new_website/blob/master/Blog_projects/2nd%20level%20PROJECTS%20desktop.psd
У цяперашнем меню Наша дзейнасць, але сама старонка будзе называцца Праекты+Клубы

## Блог
https://github.com/nastyafrosty/Falanster_new_website/blob/master/Blog_projects/2nd%20level%20PROJECTS%20desktop.psd

## Агульныя патрабаванні
1. При наведении - под карточкой появляется тень  (пример в карточке из страницы Фаланстэра). Вся карточка является активной ссылокой для перехода.
2. В Блоге видно, как по-разному отображается контент в завимиости от длины заголовка.
3. Везде - от низа картинки до нижней линии букв заголовка - 44px, от заголовка до текста 32px
![image](https://user-images.githubusercontent.com/32821205/53494029-d5122480-3aad-11e9-94df-0ec32d4617d4.png)

4. Заголовок -  Ubuntu medium, 24px, #333333
5. Текст - Pt Sans regular, 16px, #333333 НО с прозрачностью 80%

**Comment by Omeljusik** [comment]
@siarohin Вітаю,
можна браць у работу дэсктопную версію. Два макеты гатовы, трэці дадам хутчэй за ўсё заўтра. Калі з'явяцца пытанні, буду рада адказаць.

**Comment by Omeljusik** [comment]
@siarohin апішу, што адразу заўважна трэба дарабіць:
1. На старонке https://diglabby.github.io/Falanster-site/organisation.html трэба каб былі ўсе 9 картак, прэдпалагаецца, што больш ці меньш дакладна не будзе. Гэта стабільная лічба.
2. У Праекты+Клубы https://diglabby.github.io/Falanster-site/project-club.html трэба дадаць яшчэ две карткі, бо праекты могуць папаўняцца і не заўседы іх будзе змяшчацца па тры як і ў блоге. Макет https://github.com/nastyafrosty/Falanster_new_website/blob/master/Blog_projects/2nd%20level%20PROJECTS%20desktop.psd

**Comment by siarohin** [comment]
@Omeljusik https://github.com/diglabby/Falanster-site/pull/197

**Comment by Omeljusik** [comment]
@Nika987 Вітаю)
Можна глядзець.

**Comment by Nika987** [comment]
@siarohin @amoebiusss 
Привет! Ребята, подскажите, пожалуйста, как вы указываете эффект тени?!

**Comment by amoebiusss** [comment]
@Nika987 с помощью свойства box-shadow

**Comment by Nika987** [comment]
@amoebiusss 
Я правильно понимаю, эффект тени Вы указываете в пикселях, но не %? Просто мне тяжело определить этот ли эффект тени, который необходим, т.к. в ТЗ указан %.
