### ISSUE TITLE
Мобилка. Safari. Пра нас. Обрезан край фотки первого экрана

### ISSUE THREAD

**Issue by Nika987** [diglabby/Falanster-site#199]
@amoebiusss @Omeljusik @nastyafrosty 
Вложение:
Ожидаемый результат: размещена полная фотография.

P.S. Меня всегда смущали обрезанные фотки на которых видны чьи-то руки или другие части тела, возникает чувство небрежности либо то, что нет хорошей фотки.

**Comment by amoebiusss** [comment]
@Nika987 можно скрин?

**Comment by Omeljusik** [comment]
@amoebiusss @Nika987 такі варыянт падыходзіць=) 
можа потым на паляпшэнне, калі захочацца.
