### ISSUE TITLE
[Унутраная. iOs] Отличаются шрифт заголовков

### ISSUE THREAD

**Issue by Nika987** [diglabby/Falanster-site#200]
Вложение: https://monosnap.com/file/F8gzOQdV9woFJLu7o0Mzg1ytweJjPD 
Ожидаемый результат: шрифт заголовков  одинаков.

**Comment by Omeljusik** [comment]
@Nika987 Вітаю, 
пішы, калі ласка, больш канкрэтна які шрыўт чакаецца і ў чым праблема - скрына недастаткова.

**Comment by Omeljusik** [comment]
@Nika987 давай дамовімся, што ўсе праблемы з ios, акрамя таго, што верстка зусім уехала ці пераблыталіся элементы, маюць прырытэт minor.

**Comment by Nika987** [comment]
@Omeljusik @amoebiusss 
Проблема шрифта осталась в заголовках на айфоне.  Получается заголовок выделен жирным шрифтом и с тенью.

**Comment by Nika987** [comment]
@Omeljusik 
ok
