### ISSUE TITLE
[Унутраная. Смартфон і дэсктоп] Ссылки в тексте по которым осуществляем переход не соответствуют требования

### ISSUE THREAD

**Issue by Nika987** [diglabby/Falanster-site#202]
@amoebiusss 
Вложение: https://monosnap.com/file/S8KykKYGr8O0Vq2EGXuIqYvJLuNL9P 
Ожидаемый результат: согласно требованиям при нажатии на ссылку в тексте меняется шрифт на оранж и подчеркивание убирается

**Comment by amoebiusss** [comment]
@Omeljusik @Nika987 вроде бы все ок
![image](https://user-images.githubusercontent.com/26903136/53973170-4b97cd80-4111-11e9-8831-eb08f0c25bc9.png)

**Comment by amoebiusss** [comment]
https://github.com/diglabby/Falanster-site/pull/235
