### ISSUE TITLE
Мобилка. Появилась тонкая полоса между первым заголовком и текстом на всех внутренних страницах

### ISSUE THREAD

**Issue by Nika987** [diglabby/Falanster-site#203]
@amoebiusss 
Вложение: https://monosnap.com/file/jvqzv6u0KlS3kqu3tfVw7dVspNBA5W
Ожидаемый результат: отсутствует ненужные полосы

**Comment by Omeljusik** [comment]
Як рашэнне, магчыма трэба прадліць градыент. 
![image](https://user-images.githubusercontent.com/32821205/53685602-f3865300-3d2d-11e9-90c0-71a0c3864fde.png)

**Comment by Nika987** [comment]
@Omeljusik @siarohin 
Проблема осталась, и появилась еще малозаметная тонкая полоска внизу 1-го экрана.
