### ISSUE TITLE
[Унутраная. Смартфон] Выправіць выгляд кнопкі і адлегласці. Прыбраць эфекты з кнопкі.

### ISSUE THREAD

**Issue by Omeljusik** [diglabby/Falanster-site#205]
Як зараз (памер) + захаваліся эфекты з дэсктопнай версіі.

![image](https://user-images.githubusercontent.com/32821205/53685666-c4241600-3d2e-11e9-91bb-8e05bde3750a.png)

Як трэба, каб было (памер) + без эфектаў пры націску альбо "навядзенні" - проста спасылка.

![image](https://user-images.githubusercontent.com/32821205/53685720-6f34cf80-3d2f-11e9-9690-6e146bb31138.png)

**Comment by amoebiusss** [comment]
@Omeljusik  https://github.com/diglabby/Falanster-site/pull/234
