### ISSUE TITLE
 [Унутраная. Смартфон] Не бачна статус праекта ці дату на першам экране. Дата падзеі ці статус праекта павінны заўседы адлюстроўвацца ў ніжнем правам вуглу першага экрана.

### ISSUE THREAD

**Issue by Omeljusik** [diglabby/Falanster-site#206]
Так зараз:

![image](https://user-images.githubusercontent.com/32821205/53685735-a30ff500-3d2f-11e9-9417-c9a7963896a6.png)

Трэба каб было:

![image](https://user-images.githubusercontent.com/32821205/53685789-5ed12480-3d30-11e9-8c39-97e7f873bee1.png)

**Comment by Omeljusik** [comment]
@Nika987 Вітаю,
можна тэсціраваць.

**Comment by Omeljusik** [comment]
@siarohin 
на смартфоне зменаў не заўважна - статус альбо дата ўсе роўна ўнізе. 
Калі глядзець на дэсктопе памеры мабільнай версткі, то атрымліваецца. 

Дагадка ад @koverchik: Магчыма трэба каб улічваўся памер браўзера, а не ўлічваецца...

**Comment by Omeljusik** [comment]
гэта ў браўзере 

![image](https://user-images.githubusercontent.com/32821205/53739044-db374500-3ea1-11e9-8a8a-b297b5305dc6.png)

гэта на смартфоне 

![image](https://user-images.githubusercontent.com/32821205/53739072-edb17e80-3ea1-11e9-848d-73de1cc660d9.png)

**Comment by Nika987** [comment]
@Omeljusik @siarohin 
"на смартфоне зменаў не заўважна - статус альбо дата ўсе роўна ўнізе.
Калі глядзець на дэсктопе памеры мабільнай версткі, то атрымліваецца."
Я не согласна с @siarohin Отталкиваться надо от реальности, т.е. от реальных гаджетов, а не от размеров на декстопе. Потому что пользователь в первую очередь будет заходить с реального гаджета, а не с предоставляемых онлайн-сервисов, настраивая на декстопе виртуальные размеры моб версии. И если эта проблема есть и на адройде и на айфоне, значит это баг.

**Comment by siarohin** [comment]
@Nika987 С чем вы не согласны со мной? :) Проблему вижу.

**Comment by Nika987** [comment]
@siarohin 
"Калі глядзець на дэсктопе памеры мабільнай версткі, то атрымліваецца."
Я думаю, немножко некорректно отталкиваться от размеров моб версии на десктопе)

**Comment by siarohin** [comment]
@Nika987 Это не мое утверждение =) Ок
