### ISSUE TITLE
[Прамежкавая старонка] Зрабіць верстку мабільнай версіі.

### ISSUE THREAD

**Issue by Omeljusik** [diglabby/Falanster-site#210]
## Праекты+Клубы 
Макет https://github.com/nastyafrosty/Falanster_new_website/blob/master/Blog_projects/2nd%20level%20PROJECTS_mob.psd

## Блог 
Макет 
https://github.com/nastyafrosty/Falanster_new_website/blob/master/Blog_projects/2nd%20level%20BLOG_mob.psd

## Фаланстэр
Макет забылі скінуць - хутка будзе, але адрозненне ў тым, што няма ніякіх статусаў, усяго дакладна 9 картак і назва раздзела Фаланстэр. Без гарталак (1, 2, 3, ...), як у Праекты+Клубы

## Агульнае
Пры націску на картку з'яўлецца цень.

**Comment by Omeljusik** [comment]
@siarohin Аляксандр, увогуле ці патрэбен макет старонкі "Фаланстэр", альбо зразумела З апісання. Памеры ўсе застаюцца тыя ж - адрозненне толькі ў назве, без гарталак і ўсяго 9 картак.

**Comment by siarohin** [comment]
@Omeljusik Нет, не надо. В общем понятно, https://siarohin.github.io/Falanster-site/organisation.html
