### ISSUE TITLE
Мобилка. Шрифт в прямоугольнике 30px на первом экране

### ISSUE THREAD

**Issue by Nika987** [diglabby/Falanster-site#212]
Ожидаемые результат: шрифт 14px.

**Comment by Omeljusik** [comment]
@Nika987 праглядай, калі ласка, як выглядае тое, што напісана ў ТЗ. Бо @amoebiusss падбіраліся шрыўты спецыяльна такіам чынам, каб выглядала лепей. 
Па ТЗ атрыамалася б вось так

![image](https://user-images.githubusercontent.com/32821205/53827845-1e221700-3f8d-11e9-9d75-b526774dc928.png)

Гэта не тое, што нам трэба.
