### ISSUE TITLE
Мобилка. От прямоугольника нет тени

### ISSUE THREAD

**Issue by Nika987** [diglabby/Falanster-site#213]
Ожидаемый результат: есть тень

**Comment by amoebiusss** [comment]
@Nika987 @Omeljusik не совсем понимаю, о каком прямоугольнике речь. Тут тень есть:
![image](https://user-images.githubusercontent.com/26903136/53966995-66644500-4105-11e9-9c5e-d617e5fd8bc5.png)

**Comment by Omeljusik** [comment]
@amoebiusss добра, тады зачыняю.
@Nika987

**Comment by Nika987** [comment]
@Omeljusik @amoebiusss 
но визуально тени нет
