### ISSUE TITLE
Мобилка. Safari, Chrome на iOs. Проекты. Текст на странице имеет разный размер шрифта

### ISSUE THREAD

**Issue by Nika987** [diglabby/Falanster-site#215]
@amoebiusss 
Вложение: https://monosnap.com/file/zt8pIqXI7t9UBWbElVUkfvoGdL4oCg 
Ожидаемый результат: одинаковый размер шрифта текста на странице

**Comment by Omeljusik** [comment]
@Nika987 Пры якіх умовах гэта адбваецца? які браўзер, які памер экрана?

**Comment by Nika987** [comment]
@Omeljusik 
Определенных условий нет, заходишь на сайт через:
Браузеры - Safari, Chrome
с айфона с разрешением экрана 1334х750.

**Comment by Omeljusik** [comment]
@Nika987 толькі projects ці тое ж самае на кожнай унутранай?

**Comment by Omeljusik** [comment]
Толькі projects.

**Comment by Omeljusik** [comment]
от @amoebiusss праблема звязана з браўзерам, тым як ен падстрайвае шрыўты пад экран. Пакуль як вырашыць невядома.

**Comment by Nika987** [comment]
@Omeljusik @amoebiusss 
ok
