### ISSUE TITLE
Мобилка. Проекты. Не хватает кружочка и прямоугольника в Вынiкi праекта

### ISSUE THREAD

**Issue by Nika987** [diglabby/Falanster-site#216]
@siarohin 
Вложение: https://monosnap.com/file/3t3t2Gj70IdKXF9IUxeImmgJ8B8rUG
Ожидаемый результат: страница моб версии соответствует визуально десктопу
https://diglabby.github.io/Falanster-site/project

**Comment by Omeljusik** [comment]
@Nika987 мабільная версія адрозніваецца https://github.com/diglabby/Falanster-site/issues/167
