### ISSUE TITLE
Мобилка. Запись Блога. Указание автора и даты не одном уровне с заголовком

### ISSUE THREAD

**Issue by Nika987** [diglabby/Falanster-site#217]
@amoebiusss 
Вложение: https://monosnap.com/file/VqmlYrMwcmZfSBx8AcCbxUJf33ig9J
Ожидаемый результат: согласно ТЗ: указание автора и даты слева на одном уровне с заголовком

**Comment by Omeljusik** [comment]
@Nika987 па скрыну не бачу праблемы - выглядае як быццам усе па аднаму леваму краю як у ТЗ. Адзнач, калі ласка, на скрыне чырвоным у чым праблема?

**Comment by Nika987** [comment]
@Omeljusik 
https://monosnap.com/file/jn6UMXfB5dByNE4lZg5DW9mhIjDZem

**Comment by amoebiusss** [comment]
@Nika987 @Omeljusik сами текстовые блоки идут "вровень", это особенности шрифта:
![image](https://user-images.githubusercontent.com/26903136/53968157-96144c80-4107-11e9-9375-d3872022dbce.png)

Я могу добавить какой-то дополнительный отступ блоку с датой, но не факт, что это не будет выглядеть ровно, если текст поменяется. Вот например, тут выравнивается по хвостику буквы Д:
![image](https://user-images.githubusercontent.com/26903136/53968286-ca880880-4107-11e9-9eae-419ffe0b6bbf.png)

**Comment by Omeljusik** [comment]
@amoebiusss усе добра, дзякуй! 
Зачыняем іш'ю.
