### ISSUE TITLE
[Унутраная. Смартфон] Шрыўты маленькія. На макеце візуальна больш. 

### ISSUE THREAD

**Issue by Omeljusik** [diglabby/Falanster-site#224]

**Comment by Omeljusik** [comment]
@amoebiusss вітаю, 
ці наклевываецца рашэнне па гэтай праблеме?

**Comment by amoebiusss** [comment]
@Omeljusik боюсь, что не знаю, как это сделать без использования viewport-метатега, учитывающего ширину устройства. Все относительные единицы измерения либо зависят от размера шрифта корневого/родительского элемента (т.е. не будут меняться в зависимости от ширины устройства) — em, rem, %; либо зависят от ширины устройства (а она у нас не учитывается) — vw, vh. 

При это для основного текста на страницах новостей/проектов срабатывает браузерный механизм Font Boosting (https://habr.com/ru/post/214559/) и пересчитывает размер по каким-то своим алгоритмам:
![image](https://user-images.githubusercontent.com/26903136/53955346-d82e9580-40e9-11e9-9ca7-7f23f47c4675.png)
А для остального текста — почему-то не срабатывает.


На главной странице у нас всё точно так же, и не режет глаз только потому, что нет контрастных по размеру надписей: https://monosnap.com/file/J9vwR1x8LGy01OrvHKMhiMmrUs9H88

Если переделать все - не стратегия, можем просто сделать весь текст ещё крупнее.

**Comment by Omeljusik** [comment]
@amoebiusss дзякуй, не магу сказаць што дакладна зразумела праблему - з вашых слоў здаецца трэба замяняць rem, em, vh на іншыя адзінкі вымярэння.

калі перапрацоўваць, то што дакладна будзе змяняцца?   
нанаколькі шмат трэба зменяць?

**Comment by amoebiusss** [comment]
@Omeljusik напротив, я не вижу, как использование других единиц измерения может решить проблему. На мой взгляд, проблему решил бы вьюпорт-метатег с width=device-width, учитывающий ширину экрана (тут подробнее об этом: https://developer.mozilla.org/ru/docs/Mozilla/Mobile/Viewport_meta_tag)

У нас по сути все работает как в этой статье: http://wpandyou.ru/tutorials/html-css-jquery/viewport-meta-teg-dlya-ne-adaptivnogo-dizajna-sajta-non-responsive-design/

Если бы это был мой проект, я бы сделала, как предлагала в самом начале:) Заново бы сверстала.

**Comment by Omeljusik** [comment]
@siarohin @amoebiusss прапаную пакінуць існуючы варыянт.
@Nika987 @nastyafrosty

**Comment by nastyafrosty** [comment]
получается,что отображение размера шрифта полностью ложится на плечи верстальщика и дизайнер не может как-то упростить эту задачу? @amoebiusss

**Comment by amoebiusss** [comment]
@nastyafrosty да, получается так
