### ISSUE TITLE
Firefox. Декстоп. На всех внутренних и промежуточных страницах при возврате назад появляется рамка вокруг пункта главного меню

### ISSUE THREAD

**Issue by Nika987** [diglabby/Falanster-site#227]
@amoebiusss 
Вложение: https://monosnap.com/file/08ONIJIPlits2pDnCixRf908SOpsIA 
Ожидаемый результат: нет никаких рамок вокруг пунктов меню при возврате назад.

**Comment by Omeljusik** [comment]
@siarohin таксама можна вырашаць гэту праблему. 
Абыйдземся без таб.
