### ISSUE TITLE
Firefox. Футер. Всех внутренних и промежуточных страниц. По переходам по всем пунктам (Правiлы сайта...Значкi сац сетак...) и возврат обратно на страницу появляется рамка

### ISSUE THREAD

**Issue by Nika987** [diglabby/Falanster-site#228]
@amoebiusss 
Вложение: https://monosnap.com/file/X725wdS6xRFQmvSJOFiX9HcwMDLKrX
Ожидаемый результат: нет никаких рамок

**Comment by siarohin** [comment]
@Nika987 Уберу фокус -- не сможете переключаться между элементами клавишей <Tab>, подтверждаете ожидаемое поведение?

**Comment by Omeljusik** [comment]
@siarohin так, можна. Давайце прыбярэм таб, але без рамкі.

**Comment by Omeljusik** [comment]
@siarohin @Nika987 пакідаем фокус, бо прышлі да таго, што так звычайна не робіцца. 
Кастыль...
