### ISSUE TITLE
iOs. Мобилка. На всех промежуточных страниц. По переходам по значкам соц сетей и возврат обратно, пользователь оказывается на середине страницы

### ISSUE THREAD

**Issue by Nika987** [diglabby/Falanster-site#232]
@siarohin 
Ожидаемый результат: пользователя возвращает обратно в футер.

**Comment by Omeljusik** [comment]
@Nika987 можна запісь экрана? 
У мяне андройд, хром - вяртаецца ў футэр. На дэсктопе, калі гляжу таксама.

**Comment by amoebiusss** [comment]
@Nika987 @Omeljusik тоже проверила на андроиде - возвращается в футер

**Comment by Nika987** [comment]
@Omeljusik @Omeljusik 
С телефона не могу записать видео, но с айфона это так.

**Comment by Omeljusik** [comment]
Можна вяртацца да гэтага пытання, калі будзе час і жаданне. Задача не прыярытэтная.
