### ISSUE TITLE
[Прамежкавая старонка. Смартфон] Малюнак расцягваецца пад памер, які для яго выдзелены ў картке.

### ISSUE THREAD

**Issue by Omeljusik** [diglabby/Falanster-site#233]
Лепшы варыянт, калі малюнак захавае сваю цэластнасць і будзе нерасцягнутым. 
Але падыйдзе варыянт з абрэзкай малюнка:
1. Лепей - па сярэдзіне.
2. Таксама варыянт - з левага краю.

![image](https://user-images.githubusercontent.com/32821205/53959588-17161880-40f5-11e9-87ee-37b97b7e5832.png)

**Comment by siarohin** [comment]
@Omeljusik 

> Лепшы варыянт, калі малюнак захавае сваю цэластнасць і будзе нерасцягнутым.

Можете потестировать, что тогда будет: https://developer.mozilla.org/ru/docs/Web/CSS/object-fit

![Снимок](https://user-images.githubusercontent.com/38830168/54161544-28478800-445b-11e9-9b87-495420a258e6.PNG)

![Снимок_](https://user-images.githubusercontent.com/38830168/54161546-2ed5ff80-445b-11e9-8aa2-d16a13063f46.PNG)


## Стандартная реализация
**Cover**
Элемент увеличивается или уменьшается, чтобы целиком заполнить заданную область с сохранением пропорций.

PR https://github.com/diglabby/Falanster-site/pull/237

**Comment by Nika987** [comment]
@Omeljusik @siarohin 
ok
