### ISSUE TITLE
[Унутраная. iOs] Вельмі мелкі памер шрыўта і кнопкі.

### ISSUE THREAD

**Issue by Omeljusik** [diglabby/Falanster-site#236]
Фактычны рэзультат:
![image](https://user-images.githubusercontent.com/32821205/54139907-9aa47200-4433-11e9-8ab0-dc3c4cb5a7d8.png)
![image](https://user-images.githubusercontent.com/32821205/54139960-b3148c80-4433-11e9-9584-c84cc1c26e47.png)

Чакаемы рэзультат (як на андорйд).

**Comment by Nika987** [comment]
@Omeljusik @amoebiusss 
ok
