### ISSUE TITLE
Замяніць id на классы

### ISSUE THREAD

**Issue by Omeljusik** [diglabby/Falanster-site#31]
Параеўшыся з @ossset стала зразумела, што вёрстка зроблена па старым стандартам у тым ліку прастаўлены id. Трэба замяніць іх на классы.

**Comment by amoebiusss** [comment]
Изменения в этом ПР:
https://github.com/diglabby/Falanster-site/pull/44

**Comment by Nika987** [comment]
@Omeljusik @amoebiusss 
120  css/blogstyle.css
в конце перед второй фигурной скобкой пропущен знак "+"
см. вложение: https://monosnap.com/file/rUHk6115TExJnO920RnWMzajjfT9Ql 

2. 122  css/modal.css - не нашла(
3. 125  css/nav_mob.css - с мобильного не удалось просмотреть

4. 66  script.js  - все ок.

**Comment by amoebiusss** [comment]
@Nika987 не совсем поняла, о каком знаке "плюс" речь, поясните, пожалуйста

**Comment by Nika987** [comment]
@amoebiusss 
Возможно я неправильно поняла, но посмотрите плиз вложение... 
вложение: https://monosnap.com/file/w9jtBCa1KVos73A5MsQwS3AxOS8fYT

**Comment by amoebiusss** [comment]
@Nika987 плюсики/минусики — это служебные обозначения гитхаба об изменениях в файлах (т.н. diff). "-" — старое состояние измененной строки, "+" — новое. Сами файлы этих знаков не содержат

Вот, например: https://raw.githubusercontent.com/rzach/git4phi/master/changes.png
