### ISSUE TITLE
Замяніць малюнкі, якія прастаўлены ў Html як img так, каб яны былі бэкграўндамі.

### ISSUE THREAD

**Issue by Omeljusik** [diglabby/Falanster-site#32]
Параеўшыся з @koverchic стала зразумела, што вёрстка зроблена па старым стандартам у тым ліку прастаўлены img замест бэкграўндаў. Трэба замяніць.

**Comment by Omeljusik** [comment]
61PR

**Comment by siarohin** [comment]
Issue #32 has closed from #61 (https://github.com/diglabby/Falanster-site/pull/61)
