### ISSUE TITLE
Адлюстраваць розніцу паміж актыўнай і неактыўнымі мовамі згодна макету.

### ISSUE THREAD

**Issue by Omeljusik** [diglabby/Falanster-site#36]
Десктоп. При смене языков, активный должен быть 13 пикселей с интервалами между символами в 0.07, неактивный - 11 пикселей с 0.06 соответственно.

**Comment by Omeljusik** [comment]
@Nika987 можна правяраць.

**Comment by Nika987** [comment]
@Omeljusik @amoebiusss 
по интервалам все ок.
P.S. Функционал кнопок не работает, т.е. нет возможности сменить язык.
