### ISSUE TITLE
Выправіць памылкі, знойдзеныя пры валідацыі вёрсткі. Падвесці ўсю вёрстку пад найменне БЭМ

### ISSUE THREAD

**Issue by Omeljusik** [diglabby/Falanster-site#40]
Исправить выявленые ошибки при валидации https://diglabby.github.io/Falanster-site/ с помощью онлайн-сервиса  https://validator.w3.org.

**Comment by Nika987** [comment]
@Omeljusik @amoebiusss 
При валидации https://diglabby.github.io/Falanster-site/ с помощью онлайн-сервиса https://validator.w3.org:
Document checking completed. No errors or warnings to show.
Все ок.
