### ISSUE TITLE
Мобилка. Кнопка "Стань валанцёром" залазит на текст, распаложенный снизу.

### ISSUE THREAD

**Issue by Omeljusik** [diglabby/Falanster-site#45]
Мобилка. Кнопка "Стань валанцёром" залазит на текст, распаложенный снизу. Кнопка должна быть только на части "Стань валанцёрам"

**Comment by amoebiusss** [comment]
Возможно, эту кнопку стоит вообще переверстать, т.к. сейчас это вообще не кнопка и не ссылка, а текст, клик по которому обрабатывается с помощью js. Давайте обсудим изменения

**Comment by Omeljusik** [comment]
@amoebiusss так, вы можаце гэта зрабіць, калі гэта вырашае праблему і будзе нават больш проста і эфектыўна, чым праз js.

**Comment by Omeljusik** [comment]
@Nika987 можна правяраць.

**Comment by Nika987** [comment]
@Omeljusik @amoebiusss 
ok
