### ISSUE TITLE
Падвесці ўсю вёрстку пад найменне БЭМ

### ISSUE THREAD

**Issue by amoebiusss** [diglabby/Falanster-site#49]
Сейчас в верстке нет общей системы именования, классы именуются через подчеркивание, дефисы, с разной логикой присвоения названий. Может быть, определимся с общим стайлгайдом и будем придерживаться его? Это упростит последующую работу и поддержку.

**Comment by Omeljusik** [comment]
Аднолькава з #40

**Comment by Nika987** [comment]
@amoebiusss @Omeljusik 
ok
