### ISSUE TITLE
Фон навигации #3e3e3e, должен быть #333333.

### ISSUE THREAD

**Issue by Omeljusik** [diglabby/Falanster-site#50]
Десктоп і смартфон. Фон навигации (верхняе і ніжняе меню) #3e3e3e, должен быть везде #333333.

**Comment by Nika987** [comment]
@Omeljusik везде все ок, только не посмотрела код на мобилке.
@Omeljusik @siarohin 
на всякий случай, посмотрите еще это вложение 
https://monosnap.com/file/Ibbqdlu7BuHtiBj8G3fNQ2UopFlv5K
