### ISSUE TITLE
Заголовки (сами названия блоков) "Горячие проекты" и "Блог" используют #090909, должен быть #333333.

### ISSUE THREAD

**Issue by Omeljusik** [diglabby/Falanster-site#51]
Десктоп. Заголовки "Горячие проекты" и "Блог" используют #090909, должен быть #333333.

Смартфон. Заголовки  "Горячие проекты" и "Блог" используют #090909, должен быть

**Comment by Omeljusik** [comment]
Дзякуй, 
выпраўлена Заголовки (сами названия блоков) "Горячие проекты" и "Блог" используют #090909, должен быть #333333

**Comment by Omeljusik** [comment]
@siarohin Прывітанне,
выбачайце, неверна апісала заданне. Яно процеварэчывае, заўважылі? Задавайце пытанне, калі ласка, калі заўважыце, што нешта не то адбываецца. 
Тут у загалоўке #333333, а ў апісанні #1a1a1a.
Трэба, каб Блог і Гарачыя праекты мелі колер #333333.
Змяніце, калі ласка.

**Comment by Nika987** [comment]
@Omeljusik @siarohin 
декстоп: заголовок блок - ок.
               заголовок горячие проекты - 090909
Вложение: https://monosnap.com/file/TQP3CrAIoilFvQEAyKA2Dp2ydnqzAg 

мобилка: код не просмотрела(

**Comment by Nika987** [comment]
@Omeljusik @siarohin 
десктоп - ок.
