### ISSUE TITLE
В "Блоге" заголовки используют #090909, должен быть #333333.

### ISSUE THREAD

**Issue by Omeljusik** [diglabby/Falanster-site#52]
В "Блоге" заголовки используют #090909, должен быть #333333.

**Comment by siarohin** [comment]
@Omeljusik Пожалуйста, уточните задачу, в issue #51 цвет заголовка указан как #1a1a1a.

**Comment by Omeljusik** [comment]
Гэта дублюецца з #51

**Comment by siarohin** [comment]
@Omeljusik Ок, цвет заголовка остается #1a1a1a как в #51

**Comment by Nika987** [comment]
@Omeljusik @siarohin 
ok
