### ISSUE TITLE
В Safari сайт ломается 

### ISSUE THREAD

**Issue by Omeljusik** [diglabby/Falanster-site#57]
В Safari сайт ломается - ширина сайта меньше, чем ширина навигации; то бишь ширина сайта где-то 80% ширины навигации (проверял на IPhone X).
![image](https://user-images.githubusercontent.com/32821205/51840255-9f4a1680-231c-11e9-92ba-a70968ebeebe.png)

**Comment by Omeljusik** [comment]
В мобильных браузерах на айфоне Safari, Google отсутствует адаптивность верстки на мобильном устройстве с диагональю дисплея 4.7 дюйма, разрешением 1334х750 пикселей.

**Comment by Nika987** [comment]
@Omeljusik @amoebiusss 
проблема осталась

**Comment by amoebiusss** [comment]
@Nika987 кажется, починила. Прошу проверить еще раз.

тестила на виртуалке 
iPhone 7 / Safari 11.0

**Comment by Nika987** [comment]
@Omeljusik @amoebiusss 
проблема все та же, см вложение:
https://monosnap.com/file/88QhoCnffoJx9UgDTQ78riZSBYly9W 
P.S. хотя вчера около 12 ночи было все ок, только значки прыгали.

**Comment by amoebiusss** [comment]
@Nika987 нет, именно по моей ссылке :) там тестовый вариант

**Comment by amoebiusss** [comment]
@Nika987 отлично, спасибо!
