### ISSUE TITLE
Заменить p на label для связи надписи с полем ввода email

### ISSUE THREAD

**Issue by amoebiusss** [diglabby/Falanster-site#70]
Связать надпись "Падпiсацца на нас" с полем ввода емэйла с помощью лейбла (вместо абзаца):
```
<p>Падпiсацца на нас</p>
<input type="email" placeholder="Ваш e-mail">
```

**Comment by Omeljusik** [comment]
@Nika987 можна правяраць.

**Comment by Nika987** [comment]
@amoebiusss @Omeljusik 
десктоп -  ок. 
мобилка - ок.
