### ISSUE TITLE
Дэсктоп і смартфон. Замяніць лого ў верхнем меню і футаре

### ISSUE THREAD

**Issue by Omeljusik** [diglabby/Falanster-site#73]
У меню замяніць на https://github.com/nastyafrosty/Falanster_new_website/blob/master/Main%20page/%D0%BB%D0%BE%D0%B3%D0%BE%D0%BE.png

У футэре на https://wiki.falanster.info/w/images/f/fb/Logo_2018_f_trans.png

Памер і размяшчэнне адносна іншых элементаў старонкі павінны застацца як на макетах:
1. [Дэсктоп ](https://github.com/nastyafrosty/Falanster_new_website/blob/master/Main%20page/main%20desktop.psd)
2. [Смартфон](https://github.com/nastyafrosty/Falanster_new_website/blob/master/Main%20page/main_mobile.psd) 

Зараз расплываецца - бачна, што лого былі вырезаны з макетаў, а не ўстаўлены ў якасці малюнкаў без фона.

**Comment by amoebiusss** [comment]
Я поменяю изображения, но также не уверена, что зааппрувленные изменения корректны. Сейчас лого в футере - это фон. Обычно лого - это ссылка, по которой можно кликнуть и перейти на главную страницу + img в ней. Предлагаю обсудить

**Comment by Omeljusik** [comment]
@amorbiusss Вітаю,
Вы верна кажыце. Зрабіце, калі ласка, каб лого былі клікабельнымі з пераходам на "Галоўную"

**Comment by Omeljusik** [comment]
Nika987 Вітаю,
можна правяраць.

**Comment by Nika987** [comment]
@Omeljusik @amoebiusss 
ok
