### ISSUE TITLE
Дэсктоп і смартфон. Замяніць пункт меню "Наша дзейнасць" на "Дзейнасць"

### ISSUE THREAD

**Issue by Omeljusik** [diglabby/Falanster-site#74]
Дэсктоп і смартфон. Замяніць пункт меню "Наша дзейнасць" на "Дзейнасць", бо пры навядзенні пераносіцца на наступную страку

![image](https://user-images.githubusercontent.com/32821205/52162373-32e86200-26e4-11e9-879c-e86a3ad3bf47.png)

**Comment by Omeljusik** [comment]
не патрэбна, бо выпраўлена вёрстка так, каб не з'езжала.

**Comment by Nika987** [comment]
@Omeljusik @siarohin 
Десктоп: все-таки в слове "дзейнасць", концы букв смещаются вниз, а также при наведении курсора "Наша дзейнасць" дергается.
Вложение: https://monosnap.com/file/SIufpC7gpq5cfZeslbKjJ71mtUc2Rp

**Comment by amoebiusss** [comment]
@Nika987 да, т.к. мои изменения, исправляющие это, ещё не слиты с мастером

Исправлено таким образом: https://amoebiusss.github.io/Falanster-site/index.html
