### ISSUE TITLE
Дэсктоп. Блок "Гарачыя праекты". Зрабіць, каб апісанне праектаў адлюстроўвалася па леваму краю.

### ISSUE THREAD

**Issue by Omeljusik** [diglabby/Falanster-site#75]
Дэсктоп. Блок "Гарачыя праекты". Зрабіць, каб апісанне праектаў адлюстроўвалася па леваму краю згодна [макету](https://github.com/nastyafrosty/Falanster_new_website/blob/master/Main%20page/main%20desktop.psd). Зараз пасярэдзяне.

**Comment by Nika987** [comment]
@Omeljusik @siarohin - усе добра.
