### ISSUE TITLE
В блоке "Гарачыя праекты" фоновая картинка слева смещает сам блок

### ISSUE THREAD

**Issue by amoebiusss** [diglabby/Falanster-site#80]

**Comment by Omeljusik** [comment]
@siarohin зробіце, каб такога не было? 
як разумею тут таксама праблема ў тым, што малюнак як малюнак, а не бэкграўнд?

**Comment by amoebiusss** [comment]
Тут картинка как div с фоновой картинкой, но этот div спозиционирован с помощью margin, поэтому смещает соседний блок

**Comment by Nika987** [comment]
@Omeljusik @amoebiusss 
все ок
