### ISSUE TITLE
Подключение файлов стилей и шрифтов

### ISSUE THREAD

**Issue by amoebiusss** [diglabby/Falanster-site#81]
Сейчас подключено семь файлов со стилями, это не очень оптимально. Можно сгруппировать их с помощью @import и подключить единственный файл.

Плюс, в подключении шрифтов можно ограничить количество начертаний — оставить только используемые. (либо вообще не использовать cdn)

**Comment by Omeljusik** [comment]
@frenkxip @koverchik гляньце, калі ласка,  гэта праўда лепей зрабіць, так?

**Comment by koverchik** [comment]
@amoebiusss почему семь файлов это не очень оптимально? На что это влияет?
Из подключенных к странице шрифтов я вижу только "Ubuntu", "PT+Sans",  оба шрифта используются. А где лишние?

**Comment by amoebiusss** [comment]
@koverchik
7 файлов - 7 обращений к серверу вместо одного. Следовательно, снижается скорость загрузки сайта. Понятно, что файлы на гигабайтные, но тем не менее.

Не шрифтов, а их начертаний. Т.е. допустим, мы используем только нормал и болд, а подключаем все (а их может быть более десятка). Опять же вопрос скорости загрузки.

**Comment by Omeljusik** [comment]
@amoebiusss @koverchik што тут вырашылі?
@amoebiusss ці рабілі змены?

**Comment by koverchik** [comment]
1. Ничего не имею против улучшения сайта в том числе скорости загрузки страниц. Для того чтобы выяснить будет ли влиять применение import на скорость нужно проводить тесты. Я не обладаю таким ресурсом времени чтобы их провести, но автор этой статьи не очень жалует загрузку стилей через импорт (он проводил тестирование различными способами) https://habr.com/ru/post/57012/
Касаемо сервера и запросов (могу ошибаться я не эксперт в этой области), сервер в состоянии обрабатывать несколько запросов одновременно. Сервер apachе в стандартной конфигурации MaxKeepAliveRequests 100
https://httpd.apache.org/docs/2.4/mod/core.html#maxkeepaliverequests  количество запросов в данном случае не должно особо повлиять на скорость загрузки. 

2. Вопрос по шрифтам лучше обсудить в команде, ничего против лично не имею. Если дизайнер норм с  таким количеством начертаний можно делать.

**Comment by amoebiusss** [comment]
@koverchik
1. Не ставлю целью переубедить, но статья 2009 года, сейчас 2019. Информация десятилетней свежести о веб-технологиях — повод проверить актуальное состояние дел. Автор тестирует импорты в 6, 7, 8 IE, поддержка которых прекратилась три года назад.

Тогда хочу уточнить, в дальнейшей работе для каждой новой страницы мы будем подключать свой набор стилей в head-е?

2. Ок, визуально ничего не изменится, все используемые начертания останутся на месте.

@Omeljusik никаких "несанкционированных" изменений не делаю. Нужно какое-то общее решение, т.к. с Артемом @junfrenkixp обсуждали то, что лучше вообще использовать препроцессор, компилирующий все в один цсс-файл, здесь обсуждаем, что все стоит оставить как есть.

**Comment by koverchik** [comment]
@amoebiusss 
1. Процитирую саму себя "Для того чтобы выяснить, будет ли влиять применение import на скорость, нужно проводить тесты." 10 лет видела, но это не отменяет того что автор статьи компетентный чувак, который понимал что он пишет. Суть технологии за это время не поменялась.   Его труд https://the-eye.eu/public/Books/IT%20Various/high_performance_web_sites.pdf (страница 41-42) не то чтобы про скорость, скорее про проблемы связанные с использованием такого подхода.  

Мое личное мнение: смысла в таких изменениях я не вижу.  

2.  Блок с подключаемыми файлами будет дублироваться на всех страницах, должны быть подключены все используемые начертания шрифтов на всем сайте (не только на главной странице). Если этого достаточно, можно делать.

Использование препроцессоров еще обсуждались @ossset @rizoma @fr0zen решили, что не стоит использовать в проекте.

**Comment by Omeljusik** [comment]
@amorbiusss @koverchik Дзякуй,
часу няшмат, таму адсякаем усе не яснае.
Як зразумела гэта пытанне не вялікая перашкода працэ сайта. Добра, што пакінулі.
