### ISSUE TITLE
Привести в порядок css:  префиксы, отступы, порядок свойств

### ISSUE THREAD

**Issue by amoebiusss** [diglabby/Falanster-site#83]
Предлагаю использовать csscomb для приведения отступов в цсс к одному виду и для однородной группировки свойств. 

+ добавить возможно недостающие вендорные префиксы автопрефиксером. 

Это займёт немного времени, но улучшит внешний вид кода и может избавить от проблем с  небольшим процентом более старых браузеров

**Comment by Omeljusik** [comment]
+1

**Comment by amoebiusss** [comment]
https://github.com/diglabby/Falanster-site/pull/90

**Comment by Omeljusik** [comment]
@amoebiusss Вітаю,
ці гэта іш'ю таксама выканана #90?

**Comment by amoebiusss** [comment]
@Omeljusik да, верно

**Comment by Omeljusik** [comment]
@amoebiusss Дзякуй!
