### ISSUE TITLE
Прывесці верстку да БЭМ згодна каментарам у ПР 79

### ISSUE THREAD

**Issue by Omeljusik** [diglabby/Falanster-site#87]
Прывесці верстку да БЭМ згодна каментарам у ПР 79
https://github.com/diglabby/Falanster-site/pull/79

**Comment by amoebiusss** [comment]
Что насчет остальных комментариев из этого ПР?

**Comment by amoebiusss** [comment]
https://github.com/diglabby/Falanster-site/pull/90

**Comment by Omeljusik** [comment]
Бачу праблему:
Як павінна быць ![image](https://user-images.githubusercontent.com/32821205/52305802-1891db00-29a7-11e9-92b9-777afa8c88d7.png)

Як зараз на андройд Хром
![image](https://user-images.githubusercontent.com/32821205/52305851-3fe8a800-29a7-11e9-87f8-9029420d7591.png)
Праверана на сваем хуавээй таксама.

**Comment by Omeljusik** [comment]
@amoebiusss Прывітанне,
можна тэсціраваць яшчэ раз поўнасцю, бо правілася верстка.

**Comment by amoebiusss** [comment]
@Omeljusik да, ок, пересмотрю и поправлю все возможные проблемы

**Comment by Omeljusik** [comment]
@amorbiusss Добра!
Калі што адкацім змены, толькі кажыце) бо андройд для нас важней, чым айос. 
Але цікава з-за чаго ў маб. версіі верстка з'ехала і памер і жырнасць шрыўта змянілася. Можа гэта штосьці датычна БЭМ і інш. 

@Nika987 хацела вас тут затэгірваць.

**Comment by amoebiusss** [comment]
@Omeljusik нет, скорее всего при правках просто не изменено одно стилевое правило для мобилок, поправлю. Методология именования тут вообще не при чем. Правки для ios тоже не при чем, там было дело в бессмысленном использовании абсолютного позиционирования картинки в футере.

**Comment by Omeljusik** [comment]
@amoebiusss Добра, тады чакаю ПР.

**Comment by amoebiusss** [comment]
@Omeljusik https://github.com/diglabby/Falanster-site/pull/92
