### ISSUE TITLE
Нет состояний hover/focus/active у кнопки "Уваход" в шапке

### ISSUE THREAD

**Issue by amoebiusss** [diglabby/Falanster-site#88]

**Comment by Omeljusik** [comment]
@amoebiusss Што маеце на ўвазе? 
напрыклад павялічванне на 2 px пры навядзенне і загараніе аранжавым #ff6600 пры націску?

**Comment by Omeljusik** [comment]
p.s. дызайнам не прадумвалася, але і на мой погляд было б лепей, каб быў нейкі эфект, акрамя рукі.

**Comment by amoebiusss** [comment]
@Omeljusik в макете есть состояния
![image](https://user-images.githubusercontent.com/26903136/52482992-cd084880-2bc3-11e9-903e-400f9e4cec04.png)

**Comment by amoebiusss** [comment]
@Omeljusik для остальных ссылок в шапке ("запоуниць анкету", "дапамагчы") тоже есть, как оказалось

**Comment by Omeljusik** [comment]
@amoebiusss Дзякуй, што заўважылі, добра, зрабіце, калі ласка, як на макеце.
Значыць у Тз было не апісана.

**Comment by amoebiusss** [comment]
@Omeljusik в "манифесте" то же самое. дальше пока не перепроверяла, но подозреваю, что не только там

**Comment by amoebiusss** [comment]
@Omeljusik еще есть кнопка "вниз" на первом экране, ее решили не делать? или она забыта?
![image](https://user-images.githubusercontent.com/26903136/52485053-f37cb280-2bc8-11e9-88b5-6cfcb1b4f0d2.png)

**Comment by Omeljusik** [comment]
@amoebiusss оў не, гэты спуск рабіць не будзем.

**Comment by Omeljusik** [comment]
@siarohin Вырашылі: дабаўляем эфект як на макеце толькі для кнопкі Уваход.
