### ISSUE TITLE
 Ссылки. Ссылки в  тексте подчеркнутый текст.

### ISSUE THREAD

**Issue by Nika987** [diglabby/Falanster-site#91]
Согласно требованиям ТЗ:
Ссылки в тексте: 
Подчеркнутый текст 
при наведении меняется цвет текста - !!не меняется.

**Comment by amoebiusss** [comment]
@Nika987 не совсем понимаю, о какой странице речь?

**Comment by Omeljusik** [comment]
@Nika987 гэта датычна ўнутранніх старонак. На галоўнай няма спасылак у тэксце. На Галоўнай - загалоўке. А тэкст - гэта толькі Місія напачатку, апісанне гарачых праектаў і каля Стань валанцерам напрыканцы. У гэціх тэкчтах няма спасылак

**Comment by Nika987** [comment]
@Omeljusik @amoebiusss 
На галойнай старонцы есць у раздзле Блог як бы спасылка Усе падзеi цi гэта не лiчыцца спасылкай? Мне здаецца, что усе ж гэта спасылка. калi так, тады я зравблю новае i ш'ю!?
