### ISSUE TITLE
Дэсктоп і Смартфон. Падлучыць падпіску. 

### ISSUE THREAD

**Issue by Omeljusik** [diglabby/Falanster-site#93]
Лепшы варыянт. Чалавек уводзіць у наша поле свой email, націскае ок і праз гэта падпісваецца на рассылку (яму прыходзіць паведамленне на пошту з мэйлчымпа, каб ен скончыў завязку на падпіску) -> З'яўляецца наша поп-ап старонка, дзе трэба націснуць Добра. Калі адрас уведзены не існуючы, то пры націску поле загараецца чырвоненькім па краю #e85c41
Зверстаная намі поп-ап старонка з Добра, з'яўдяецца толькі пры паспяховай падпіске. Пры простым націску не з'яўляецца.

![image](https://user-images.githubusercontent.com/32821205/52394829-cfcc4600-2abc-11e9-91e3-9082f38b5beb.png)

Калі не атрымаецца лепшы варыянт, то хопіць таго, што пры ўводзе вернага адраса і націску Ок адбываецца падпіска (адсылаецца ліст на мэйл) і  пераход на дэфолтную старонку от майлчымпа пра тое, што падпіска амаль завершына. (код з поп-ап можна закаментаваць да лепшага часу, калі хто захоча гэцім заняцца). Калі адрас уведзены не існуючы, то пры націску поле па краю становіцца чырвоненькім #e85c41. 

![image](https://user-images.githubusercontent.com/32821205/52394874-fdb18a80-2abc-11e9-8f1e-be754dc89c1b.png)

Як выглядае стандартная форма
![image](https://user-images.githubusercontent.com/32821205/52395088-d60ef200-2abd-11e9-8d05-04169fc5d474.png)

Код для яе ўстаўкі, які трэба правіць пад нашу верстку ў Футэре:
https://github.com/Omeljusik/Hello-world/blob/master/form_mailchimp.txt

**Comment by Omeljusik** [comment]
https://github.com/diglabby/Falanster-site/pull/98 зроблена

**Comment by Omeljusik** [comment]
@siarohin @amoebiusss Вітаю,
гэту задачу закрылі.

@Nika967 пратэсціруйце, калі ласка. Форма падлучана па другому варыянту ў апісанні іш'ю.

**Comment by Nika987** [comment]
@Omeljusik 
Не могу найти форму: 
"Форма падлучана па другому варыянту ў апісанні іш'ю."
