### ISSUE TITLE
Выправіць поп-ап старонку ў футаре ў поле падпіску, якая з'яўляецца пры націску Ок. Смартфон і Дэсктоп.

### ISSUE THREAD

**Issue by Omeljusik** [diglabby/Falanster-site#94]
Дэсктоп.
Вакенца знікае:
- пры націску на Добра
- пры націску на шэрую вобласць за ім.
- пры націску на enter
- пры націску на esc
Пры націску на поле самаго вакенца, нічога не адбываецца.

https://github.com/diglabby/Falanster-site

Паведамленне пасля націску на "Ок" павінна з'яўляцца толькі пры ўводзе карэктнага email і падключэння да падпіскі.

Смартфон:
Вакенца адчыняецца амаль на весь экран 
![image](https://user-images.githubusercontent.com/32821205/52395339-c9d76480-2abe-11e9-9525-6a0fc6eda365.png)

Зараз так 
![image](https://user-images.githubusercontent.com/32821205/52395353-dd82cb00-2abe-11e9-919f-c81bbdfa4988.png)

**Comment by siarohin** [comment]
@Omeljusik https://github.com/diglabby/Falanster-site/pull/96
