### ISSUE TITLE
Дэсктоп. Сверстаць унутранніі старонкі (старонка пра арганізацыю, Блог, Афіша)

### ISSUE THREAD

**Issue by Omeljusik** [diglabby/Falanster-site#97]
### Брейкпоинты

Десктоп  - > 1080 px
Смартфон - 320px - 1080px

## ДЕСКТОП
Размеры ширин областей с текстом
Для Десктоп  ширина области текста 990px, 
Для Смартфон - 640 px (89% от всей ширины)

Все прямоугольные формы (кнопки, блоки проектов) имеют закругление в 3px

### ПЕРВЫЙ ЭКРАН

1.Первый экран - на всю ширину и высоту экрана пользователя. На экран заливается слой серым 333333, непрозрачность 70% .

2.Шрифт заголовка: Ubuntu, medium, 60px, межстрок (если не вмещается на одну строку, перенос по словам)- 72px. Заголовок выравнивается по середине ширины. Определить область для заголовока, выравнять посередине (чтобы заголовок при переносе слов оставался по-середине, а не уезжал вверх или вниз) 

3.Прямоугольник: 233 (ширина) х 86 (высота)px, цвет,как и всегда темно-серый 333333, шрифт в нем Ubuntu Medium 20px. Расстояние от даты или статуса проекта до иконки - 20px, вместе они выровнены по центру высоты и ширины прямоугольника. есть тень тень прямоугольника с датой мероприятия и статусом проекта

4.Низ стрелки находится на уровне низа прямоугольника 20px

5.Диаметр кружка со стрелкой (вправо,влево,вниз) - 40px. боковые кружки находятся на расстоянии 74px от рабочей области. низ на одной линии с заголовком (его одной строки либо второй нижней)

6. Низ заголовка находится на расстоянии 292px от меню сверху. Нужно определить область для заголовока, чтобы он выравнивался посередине, а не уползал вверх, если в заголовке несколько строк. 

7.Указание автора и даты - 60px от заголовка, шрифт Ubuntu Regular 14px. от даты до автора 40px. Слева на одном уровне с заголовком

### СТАТЬЯ/ОПИСАНИЕ ПРОЕКТА/ЗАПИСЬ В БЛОГЕ

Рабочая область тут - 778px

Строка текста появляется на расстоянии 120 px от высоты "второго" экрана до серого меню, которое остается закрепленным. 

Head 1 - PT Sans Bold 24px, 333333
Head 2 - PT Sans Bold 20 px, 333333
Text - PT Sans Regular 16px, межстр 22px, 333333

Cсылки: ссылка в тексте - 333333 подчеркнута, при наведении оранжевый ff6600 подчеркнута, при нажатии оранжевая и подчеркивание убирается

Расстояние

от Head 1 до текста - 56px
до Head 1 - 72px
от текста до Head 2 - 48px
от Head 2 до текста - 36 px
от текста до картинки - 48px (если относится к конкретному блоку), 64 - если ко всему тексту целиком
абзац - 32px

Картинка максимум - 778px ширина
От картинки или текста до кнопки - 72 px
От чего-то до футера 110px
От чего-то до виджета с коментами - 80px

Кнопка call to action:
Дэсктоп: 420х64, Ubuntu 18,bold
Мабільная версія: на всю ширину рабочей области (720px), Ubuntu 28,bold
Фон:  #ff6600 
Колер шрыўта: белы

## Для старонак Пра арганізацыю
Пры націску на стрэлку "Уніз" на першам экране адбываецца скрол на другі экран (з асноўным тэкстам).

## Для праектаў
Статус праекта ці клуба:
Бягучы
Спынены
Скончаны
Гарачы праект
Значкі тут https://github.com/nastyafrosty/Falanster_new_website/tree/master/Blog_projects

## Для запісаў Блога
У шэрым прамавагульнікі выводзіцца дата падзеі.
Пры націску на стрэлку "Уніз" на першам экране адбываецца скрол на другі экран (з асноўным тэкстам).
Пры націску ўлева-управа адбываецца пераход на папярэдні-наступны запіс Блога (не па кругу - да канца ўлева і ўправа). Прыклад тут https://it.falanster.by/blog/2019/01/28/data-detox/

## Карысныя матэрыялы:
1. Макеты https://github.com/nastyafrosty/Falanster_new_website/tree/master/Blog_projects
2. Макет з параметрамі адлегласцей https://github.com/Omeljusik/Hello-world/blob/master/pixels.png
3. Агульнае ТЗ https://docs.google.com/document/d/11vrJMGsbj9pUZvviJvD_RbJlmZrumwtCvAWlaYlOwK0/edit#

**Comment by Omeljusik** [comment]
@Nika987 Прывітанне, Вераніка,
можна правяраць старонку Пра нас (старонкі пра арганізацыю) https://amoebiusss.github.io/Falanster-site/about.

**Comment by Omeljusik** [comment]
@nastyafrosty Калі ласка, глянь старонку https://amoebiusss.github.io/Falanster-site/about напішы ў threads свае заўвагі. Мяне больш за ўсё цікавіць эфект кнопачкі напрыканцы. Мабыць 
як тут чытаць далей https://diglabby.github.io/Falanster-site/?

**Comment by nastyafrosty** [comment]
@Omeljusik учитывая,что такой же эффект,как на главной, еще в хэдере,то нужно везде одинаково сделать...
а так здорово!

**Comment by Omeljusik** [comment]
@nastyafrosty а пры націску таксама становіцца белай, а тэкст аранжавым. Нічога будзе выглядаць, бо не будзе межаў на белам фоне, вльбо зрабіць нейкую рамку ці пакінуць толькі эфект павілячжэння пры навядзенні?

**Comment by nastyafrosty** [comment]
@Omeljusik на самом деле,кажется, что увеличивающаяся кнопка более редкое явление,обычно так увеличиваются другие элементы (например,карточки)

**Comment by Omeljusik** [comment]
@nastyafrosty Дык, якое тады рашэнне? 
Я б пакінула як на Галоўнай "Чытаць пра нас" прв навядзенні і пры начціску абратны змен колера шрыўта і бэкграўнда + аранжывая рамка.
Албо толькі павілячэнне пры навядзенні. 

Калі есць нешта іншае, то напішы, калі ласка, але канкрэтны варыянт. Альбо прапаную адзін з сваіх.

**Comment by nastyafrosty** [comment]
@Omeljusik ладно,давай как на главной,но без рамки, т.е. ровно как есть. у нас же не должно быть все как обычно, а так пользователю итак все понятно

**Comment by Omeljusik** [comment]
@nastyafrosty добра.

**Comment by Omeljusik** [comment]
@amoebiusss Вырашылі, што кнопкі павінны быць як на Галоўнай "Чытаць пра нас".

**Comment by amoebiusss** [comment]
@Omeljusik 
пока страницы на моем тестовом:
https://amoebiusss.github.io/Falanster-site/about.html 
https://amoebiusss.github.io/Falanster-site/project.html
https://amoebiusss.github.io/Falanster-site/event.html


есть вопрос, как именно будет реализован слайдер в проектах? это именно переключение между проектами? т.е. просто ссылки?

**Comment by Omeljusik** [comment]
@amoebiusss Вітаю, дзякуй,
адказваю наконт слайдэра - гэта пералістванне менавіта запісаў блога (не праектаў!) і трэба ўлічваць, што запісы не статычны і іх колькасць будзе пастаянна павялічвацца. 

@Nika987 можна тэсціраваць старонкі https://amoebiusss.github.io/Falanster-site/event.html і https://amoebiusss.github.io/Falanster-site/project.html

**Comment by Nika987** [comment]
@Omeljusik 
Пытанне: запамятавала спытаць, тэставанне на мабiльцы рабiць? Бо бачыла толiкi макет веб цi ужо ёсць макет мобikлki?

**Comment by Omeljusik** [comment]
@Nika987 Вітаю, не, пакуль не трэба, тут нават у іш'ю напісана Дэсктоп. 
Хутка ствару асобную іш'ю пад мбілку.

**Comment by amoebiusss** [comment]
@Omeljusik 
> адказваю наконт слайдэра - гэта пералістванне менавіта запісаў блога (не праектаў!) і трэба ўлічваць, што запісы не статычны і іх колькасць будзе пастаянна павялічвацца.

не совсем понимаю про количество. по сути это ведь ссылки на страницы с другими урлами, разве не так?

**Comment by nastyafrosty** [comment]
Изменились отступы, проверьте,пожалуйста . Десктоп версия 7.Указание автора и даты - 60px от заголовка, шрифт Ubuntu Regular 14px. от даты до автора 40px. Слева на одном уровне с заголовком

**Comment by nastyafrosty** [comment]
![image](https://user-images.githubusercontent.com/41231823/53287660-7c324b80-3790-11e9-992b-8ebe93c367c8.png)
тень серого прямоугольника с датой и статусом проекта

**Comment by Omeljusik** [comment]
@amoebiusss Вітаю,
увогуле не трэба рабіць стрэлке для запісаў блога Улева-управа - вырашылі, што гэта лішняе. Калі што, то будзе на паляпшэнне. 
![image](https://user-images.githubusercontent.com/32821205/53287666-8fddb200-3790-11e9-8450-dafaa677fce7.png)

**Comment by amoebiusss** [comment]
@Omeljusik убрала ссылки https://github.com/diglabby/Falanster-site/pull/171
